info:
  app:
    name: "Bot"
    description: "The main bot Discord application."
    version: "1.0.0"


server:
  port: ${BOT_API_PORT:9000}

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
#            - shardsReadiness
        liveness:
          include:
            - livenessState
#            - shardsLiveness
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /docs/openapi.json

scalar:
  enabled: true
  url: /docs/openapi.json
  path: /docs
  page-title: "Astro bot-API Reference"
  operation-sorter: method

##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://16d5963ef1bc772e7881083afe2807d8@o4506708022263808.ingest.sentry.io/4506708023967744
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.05

spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://localhost:27017/AstroLocal}
  data:
    mongodb:
      auto-index-creation: true
    redis:
      client-name: bot
      client-type: lettuce
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}

discord:
  application:
    id: ${DISCORD_APPLICATION_ID:788708323867885568}
    token: ${DISCORD_APPLICATION_TOKEN:}
    activity-type: ${DISCORD_APPLICATION_ACTIVITY_TYPE:CUSTOM_STATUS}
    activity-text: ${DISCORD_APPLICATION_ACTIVITY_TEXT:/help | astro-bot.space}
