[versions]
# Build tooling
jib = "3.5.4"
ksp = "2.3.3"

# Kotlin
kotlin = "2.4.0"
kotlinxCoroutines = "1.11.0"
kotlinxDatetime = "0.8.0"
kotlinxSerialization = "1.11.0"

# Core
guava = "33.6.0-jre"
nanoid = "2.0.0"
datetime = "0.7.1"

# Spring
springDependencyManagementPlugin = "1.1.7"
springBootPlugin = "4.1.0"

# Logging and monitoring
sentryPlugin = "6.14.0"
sentry = "8.52.0"
kotlin-logging = "8.0.4"
logback = "1.6.1"

# Database
mongo = "5.9.1"

# Serialization
jackson-kotlin = "2.22.1"
jackson-date = "2.22.1"

# Concurrency
coroutines = "1.10.2"

# Security
jjwt = "0.13.0"

# Caching
# TODO: replace with Jedis
caffeine = "3.2.4"
lettuce = "7.6.0.RELEASE"

# Integrations
chargebee = "4.14.0"
jda = "6.5.0"
jda-ktx = "0.15.0"

# Analytics
bigquery = "2.69.0"

# Testing
junit = "6.1.2"

[libraries]
# BUILD PLUGINS
kotlin-jvm-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
kotlin-spring-plugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin" }
spring-boot-plugin = { module = "org.springframework.boot:org.springframework.boot.gradle.plugin", version.ref = "springBootPlugin" }
spring-dependency-management-plugin = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version.ref = "springDependencyManagementPlugin" }
jib-plugin = { module = "com.google.cloud.tools.jib:com.google.cloud.tools.jib.gradle.plugin", version.ref = "jib" }
sentry-plugin = { module = "io.sentry.jvm.gradle:io.sentry.jvm.gradle.gradle.plugin", version.ref = "sentryPlugin" }

# PLATFORM BOMS
mongo-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongo" }

# DEPENDENCIES
# Database
mongo-driver = { module = "org.mongodb:mongodb-driver-kotlin-coroutine" }
mongo-bson-kotlinx = { module = "org.mongodb:bson-kotlinx" }

# Core
guava = { module = "com.google.guava:guava", version.ref = "guava" }
nanoid = { module = "com.aventrix.jnanoid:jnanoid", version.ref = "nanoid" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

# Spring
spring-core = { module = "org.springframework:spring-core" }
spring-context = { module = "org.springframework:spring-context" }
spring-boot = { module = "org.springframework.boot:spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis"}
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

# Logging and monitoring
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
sentry = { module = "io.sentry:sentry-spring-boot-starter", version.ref = "sentry" }

# Serialization
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-kotlin" }
jackson-date = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-date" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Concurrency
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }

# Security
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Caching
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }

# Integrations
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jda-ktx = { module = "club.minnced:jda-ktx", version.ref = "jda-ktx" }
chargebee = { module = "com.chargebee:chargebee-java", version.ref = "chargebee" }

# Analytics
bigquery = { module = "com.google.cloud:google-cloud-bigquery", version.ref = "bigquery" }

# Testing
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

[bundles]
service-core=[
    "spring-boot-starter",
    "spring-boot-starter-webflux",
    "spring-boot-starter-actuator"
]
coroutines=[
    "coroutines-core",
    "coroutines-reactor"
]
logging=[
    "kotlin-logging",
    "logback"
]
cache=[
    "spring-boot-starter-data-redis"
]
db=[
    "mongo-driver",
    "mongo-bson-kotlinx"
]