info:
  app:
    name: "Central API"
    description: "Main REST API for Astro"

logging:
  level:
    root: ${CA__LOG_LEVEL}

server:
  port: ${CA__PORT}


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


springdoc:
  api-docs:
    path: /docs/openapi.json

scalar:
  enabled: true
  url: /docs/openapi.json
  path: /docs
  page-title: "Astro API Reference"
  operation-sorter: method


sentry:
  dsn: https://16d5963ef1bc772e7881083afe2807d8@o4506708022263808.ingest.sentry.io/4506708023967744
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.05


#####################
# CUSTOM PROPERTIES #
#####################

### SHARED ###

chargebee:
  enabled: true
  site-name: ${CHARGEBEE_SITE_NAME}
  api-key: ${CHARGEBEE_API_KEY}
  server-ultimate-plan-id: ${CHARGEBEE_SERVER_PREMIUM_PLAN_ID}

discord:
  api:
    base-url: ${DISCORD_API_BASE_URL}
    enabled: true
  oauth:
    id: ${DISCORD_OAUTH_ID}
    secret: ${DISCORD_OAUTH_SECRET}
    redirect-uri: ${DISCORD_OAUTH_REDIRECT_URI}

bot:
  endpoint:
    localhost: ${BOT_ENDPOINT_LOCALHOST}
    port: ${BOT_API_PORT}
    pod-name: ${BOT_ENDPOINT_POD_NAME}
    service-name: ${BOT_ENDPOINT_SERVICE_NAME}
    namespace: ${BOT_ENDPOINT_NAMESPACE}
  shard:
    manager:
      total-shards: ${BOT_SHARD_MANAGER_TOTAL_SHARDS}
      total-pods: ${BOT_SHARD_MANAGER_TOTAL_PODS}
      login-factor: ${BOT_SHARD_MANAGER_LOGIN_FACTOR}

frontend:
  base-url: ${FRONTEND_BASE_URL}

r2:
  endpoint-url: ${R2_ENDPOINT_URL}
  access-key-id: ${R2_ACCESS_KEY_ID}
  secret-access-key: ${R2_SECRET_ACCESS_KEY}
  bucket-name: ${R2_BUCKET_NAME}

### SERVICE SPECIFIC ###

central:
  api:
    auth: ${CA__AUTH:}
    session-cookie-name: ${CA__SESSION_COOKIE_NAME}
    session-cookie-allow-origin: ${CA__SESSION_COOKIE_ALLOW_ORIGIN}
    session-cookie-domain: ${CA__SESSION_COOKIE_DOMAIN}
    session-cookie-secure: ${CA__SESSION_COOKIE_SECURE}
    session-cookie-same-site: ${CA__SESSION_COOKIE_SAME_SITE}
    cors-allowed-origins:
      - ${CA__CORS_ALLOWED_ORIGIN}
