apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-load-certificates
  namespace: kube-system
spec:
  tls:
    - hosts:
        - “*.astro-bot.space"
      secretName: tls
  rules:
    - host: “*.astro-bot.space"
